In [2]:
import numpy as np
mu_1 = 1/4*np.array([1,1])
mu_2 = 1/4*np.array([3,1])
mu_3 = 1/4*np.array([2,3])
mu = np.array([mu_1,mu_2,mu_3])

sig_1 = 0.01*np.eye(2)
sig_2 = np.copy(sig_1)
sig_3 = np.copy(sig_1)
sig = np.array([sig_1,sig_2,sig_3])

print(mu)
print(sig.shape)

print(np.random.uniform(low=0, high=4, size=(5, 2)))



[[0.25 0.25]
 [0.75 0.25]
 [0.5  0.75]]
(3, 2, 2)
[[0.0906579  3.74754966]
 [1.08984721 0.72013018]
 [0.15383507 2.08039481]
 [0.76200547 0.33564612]
 [0.56158501 3.08660782]]


In [3]:
for i in range(2,-1,-1):
    print(i)

2
1
0


In [8]:
idx_sigma = np.random.randint(0, 3, 4)
idx_sigma

array([2, 2, 2, 1])