In [2]:
import numpy as np

arr = np.array([[1,2,3],[2,3,4]])
print(np.mean(arr,axis = 0))


[1.5 2.5 3.5]


In [3]:
np.ones(3)

array([1., 1., 1.])

In [4]:
K = 3
sigma = [np.eye(2) for k in range(K)]
sigma

[array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [0., 1.]])]

In [5]:
[print(k) for k in range(3)]

0
1
2


[None, None, None]

In [6]:
arr = np.ones(4)*3

arr == 3

array([ True,  True,  True,  True])

In [7]:
np.exp(-40)

4.248354255291589e-18

In [8]:
(2*np.pi)**(784/4)*(2*np.pi)**(784/4)

inf

In [11]:
np.zeros([6,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])