In [9]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
x = np.array([1,2,3,4])

X1 = np.tile(x,(len(x),1))
print(X1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [11]:
np.random.rand(6)

array([0.70864831, 0.08171591, 0.74625195, 0.70845557, 0.96532157,
       0.82344089])

In [12]:
R = 1
z_j = np.array([np.random.uniform(0,2*np.pi) for r in range(R)])
print(z_j)

[0.98116536]


In [14]:
N = 4
D = 2
X = np.ones((N,D))
X[:,0] = np.linspace(-3.,3.,N)
X[:,1] = np.sort(np.random.randn(N))

print(X)
print(X[np.random.choice(np.arange(0,X.shape[0]),2)])
print(X[np.random.choice(X.shape[0], 2)])
np.arange(0,X.shape[0])


[[-3.         -1.34968629]
 [-1.         -0.82245135]
 [ 1.         -0.55543474]
 [ 3.          1.2452958 ]]
[[-3.         -1.34968629]
 [-3.         -1.34968629]]
[[-3.         -1.34968629]
 [ 1.         -0.55543474]]


array([0, 1, 2, 3])