In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x = np.array([1,2,3,4])

X1 = np.tile(x,(len(x),1))
print(X1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [4]:
np.random.rand(6)

array([0.1015625 , 0.05297886, 0.74603636, 0.178796  , 0.11895683,
       0.58359243])

In [10]:
R = 1
z_j = np.array([np.random.uniform(0,2*np.pi) for r in range(R)])
print(z_j)

[2.26114648]
